services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env

  bot:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: